### ISSUE TITLE
cascading worldgen lag

### ISSUE THREAD

**Issue by xronin01** [kotmatross28729/EnviroMine-continuation#3]
[latest.log](https://github.com/kotmatross28729/EnviroMine-continuation/files/13759498/latest.log)

**Comment by kotmatross28729** [comment]
1) https://github.com/embeddedt/ArchaicFix/issues/75
2) Cascading worldgen, in fact, is not a bug as such, it is more a “""feature""” of 1.7.10.
This is because the mod forces additional chunk(s) to be loaded, and apparently cannot be "fixed". In the best case you can disable enviromine generation, but I am more than sure that it doesn't cause "cascading worldgen", because **it is even in vanilla 1.7.10, without forge** (mods just make it more visible)
